# Generated by Django 4.2.1 on 2023-05-08 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=8)),
                ("complement", models.TextField(null=True)),
                ("district", models.CharField(max_length=50)),
            ],
        ),
    ]
