# Generated by Django 4.2.1 on 2023-05-08 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=30)),
                ("name", models.TextField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.IntegerField()),
                ("description", models.TextField(null=True)),
                ("is_avaliable", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
